apiVersion: apps/v1
kind: Deployment
metadata:
  name: skolni-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skolni-app
  template:
    metadata:
      labels:
        app: skolni-app
    spec:
      containers:
      - name: skolni-app
        # Tady je vase adresa image:
        image: ghcr.io/tomasgebauer00/skolni-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          value: "tajne-heslo"